// src/components/ReactiveLink.svelte
<script lang="ts">
    export let angle = 0;
    export let color = "#000";
    export let href: string;
    export let title = "";
</script>

<a rel="noopener noreferrer"
    style="--angle:{angle}deg; --color: {color};"
    href="{href}"
    title="{title}"
>
    <slot />
</a>

<style>
	a {
        border-radius: 50%;
        color: var(--icon);
        display: inline-block;
        overflow: hidden;
        pointer-events: all;
        transform: rotate(var(--angle)) scale(1);
        will-change: opacity, transform;
        transition: opacity 0.2s ease-in-out, transform 0.2s ease-in-out;
	}

    a:hover,
    a:focus {
        outline: 0;
        transform: rotate(var(--angle)) scale(1.1);
    }

    a:hover,
    a:focus {
        color: var(--color);
    }
</style>

// src/components/ReactiveLink/ReactiveLink.tsx
import { css, cx } from "emotion";
import React, { FC } from "react";
import ReactiveLinkProps from "./ReactiveLinkProps";

export const ReactiveLink: FC<ReactiveLinkProps> = ({
  angle = 0,
  children,
  className,
  ...props
}) => (
  <a
    className={cx(
      css`
        border-radius: 50%;
        display: inline-block;
        overflow: hidden;
        pointer-events: all;
        transform: rotate(${angle}deg) scale(1);
        will-change: opacity, transform;
        transition: opacity 0.2s ease-in-out, transform 0.2s ease-in-out;

        &:hover,
        &:focus {
          outline: 0;
          transform: rotate(${angle}deg) scale(1.1);
        }
      `,
      className
    )}
    rel="noopener noreferrer"
    {...props}
  >
    {children}
  </a>
);

export default ReactiveLink;
